"""refactor user table

Revision ID: 8f647f2be95e
Revises: 9bb11d776d43
Create Date: 2023-12-18 11:53:32.667783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f647f2be95e'
down_revision: Union[str, None] = '9bb11d776d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_table('user_roles')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_fkey', 'users', 'user_roles', ['role'], ['id'])
    op.drop_column('users', 'is_admin')
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey')
    )
    # ### end Alembic commands ###
